# Generated by Django 4.1.2 on 2022-10-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('nama', models.CharField(max_length=255)),
                ('bidang', models.CharField(default='Programming', max_length=255)),
                ('nim', models.CharField(max_length=255)),
                ('progres', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
