# Generated by Django 4.1.2 on 2022-10-16 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='jenis',
            field=models.CharField(default='berita', max_length=255),
        ),
        migrations.AddField(
            model_name='pos',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
